from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from code2env.executor import run_symbol_subprocess
from code2env.indexer import find_candidate, index_repo
from code2env.models import EnvSpec, FunctionCandidate, RepoSnapshot, ToolSpec


def draft_env_spec(
    snapshot: RepoSnapshot,
    *,
    symbol: str,
    fixture: dict[str, Any] | None = None,
    env_id: str | None = None,
    compute_golden: bool = True,
) -> EnvSpec:
    candidates = index_repo(snapshot)
    candidate = find_candidate(candidates, symbol)
    normalized_fixture = _normalize_fixture(fixture)
    source = {
        "repo": snapshot.source,
        "source_root": snapshot.path,
        "commit": snapshot.commit,
        "entrypoint": candidate.symbol,
        "file": candidate.file,
        "line_start": candidate.lineno,
        "line_end": candidate.end_lineno,
        "license_file": snapshot.license_file,
    }
    spec = EnvSpec(
        id=env_id or _default_env_id(candidate, snapshot),
        version=1,
        source=source,
        task=_task_from_candidate(candidate),
        tools=_tools_from_candidate(candidate),
        runtime={
            "max_steps": 8,
            "timeout_seconds": 3,
            "sandbox": {
                "network": False,
                "subprocess": "disabled",
                "filesystem": "package_or_snapshot_readonly",
            },
        },
        reward={
            "type": "exact_match",
            "oracle": "pinned_source_function",
            "weights": {
                "schema_validity": 0.05,
                "process_progress": 0.20,
                "final_correctness": 0.65,
                "efficiency": 0.05,
                "safety": 0.05,
            },
        },
        fixture=normalized_fixture,
        golden_answer=None,
        provenance={
            "task_sources": [
                {
                    "kind": "source_span",
                    "path": candidate.file,
                    "symbol": candidate.symbol,
                    "line_start": candidate.lineno,
                    "line_end": candidate.end_lineno,
                }
            ],
            "metrics": candidate.metrics,
            "risk_flags": candidate.risk_flags,
            "helper_candidates": candidate.helper_candidates,
        },
    )
    if compute_golden:
        spec.golden_answer = run_symbol_subprocess(
            snapshot.path,
            candidate.symbol,
            list(normalized_fixture["args"]),
            dict(normalized_fixture["kwargs"]),
            disable_network=True,
            disable_subprocess=True,
        )
    return spec


def _normalize_fixture(fixture: dict[str, Any] | None) -> dict[str, Any]:
    fixture = dict(fixture or {})
    args = fixture.get("args", [])
    kwargs = fixture.get("kwargs", {})
    if not isinstance(args, list):
        raise ValueError("fixture args must be a list")
    if not isinstance(kwargs, dict):
        raise ValueError("fixture kwargs must be an object")
    return {"args": args, "kwargs": kwargs}


def _default_env_id(candidate: FunctionCandidate, snapshot: RepoSnapshot) -> str:
    digest = hashlib.sha256(
        f"{snapshot.source}:{snapshot.commit}:{candidate.symbol}".encode("utf-8")
    ).hexdigest()[:8]
    clean_symbol = re.sub(r"[^a-zA-Z0-9_.-]+", ".", candidate.symbol.replace(":", "."))
    return f"code2env.{clean_symbol}.{digest}.v1".lower()


def _task_from_candidate(candidate: FunctionCandidate) -> dict[str, Any]:
    title = f"Run and match `{candidate.symbol}`"
    doc = candidate.docstring.splitlines()[0] if candidate.docstring else ""
    instruction = (
        f"Use the available tools to execute `{candidate.symbol}` with the provided fixture "
        "and submit the exact result payload that matches the pinned source implementation."
    )
    if doc:
        instruction += f" Source docstring summary: {doc}"
    return {
        "title": title,
        "instruction": instruction,
        "entrypoint": candidate.symbol,
        "success_criteria": [
            "Submitted answer exactly matches the golden answer generated by the pinned source function.",
            "Tool arguments are valid JSON objects.",
            "The episode finishes within the step budget.",
        ],
        "constraints": [
            "Do not perform real network operations from generated tools.",
            "Only call tools exposed by this environment.",
        ],
    }


def _tools_from_candidate(candidate: FunctionCandidate) -> list[ToolSpec]:
    tools = [
        ToolSpec(
            name="inspect_task",
            description="Return the task, fixture, source metadata, and available helper names.",
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={"type": "object"},
        ),
        ToolSpec(
            name="call_entrypoint",
            description="Execute the selected source entrypoint with JSON args and kwargs.",
            input_schema={
                "type": "object",
                "properties": {
                    "args": {"type": "array"},
                    "kwargs": {"type": "object"},
                },
                "additionalProperties": False,
            },
            output_schema={"type": "object"},
            timeout_ms=3000,
        ),
    ]
    if candidate.helper_candidates:
        tools.append(
            ToolSpec(
                name="call_helper",
                description="Execute an allowed top-level helper from the same module.",
                input_schema={
                    "type": "object",
                    "required": ["helper"],
                    "properties": {
                        "helper": {"type": "string", "enum": candidate.helper_candidates},
                        "args": {"type": "array"},
                        "kwargs": {"type": "object"},
                    },
                    "additionalProperties": False,
                },
                output_schema={"type": "object"},
                timeout_ms=3000,
            )
        )
    tools.append(
        ToolSpec(
            name="submit_answer",
            description="Submit the final serialized answer payload for exact-match scoring.",
            input_schema={
                "type": "object",
                "required": ["answer"],
                "properties": {"answer": {"type": "object"}},
                "additionalProperties": False,
            },
            output_schema={"type": "object"},
        )
    )
    return tools


def source_root_for_spec(spec: EnvSpec, package_root: str | Path | None = None) -> Path:
    raw_root = Path(str(spec.source["source_root"]))
    if raw_root.is_absolute():
        return raw_root
    if package_root is None:
        return raw_root.resolve()
    return (Path(package_root).resolve() / raw_root).resolve()
